# Generated by Django 4.2.25 on 2025-10-17 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('tipo', models.CharField(choices=[('DOCUMENTO', 'Documento'), ('IMAGEM', 'Imagem'), ('PLANILHA', 'Planilha'), ('PDF', 'PDF'), ('OUTRO', 'Outro')], default='DOCUMENTO', max_length=20, verbose_name='Tipo')),
                ('arquivo', models.FileField(upload_to='documentos/%Y/%m/', verbose_name='Arquivo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('data_envio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Envio')),
                ('tamanho', models.BigIntegerField(blank=True, null=True, verbose_name='Tamanho (bytes)')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-data_envio'],
            },
        ),
        migrations.CreateModel(
            name='Encaminhamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condicao', models.CharField(blank=True, help_text='Ex: Aprovado, Rejeitado, Precisa Revisão', max_length=200, verbose_name='Condição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
            ],
            options={
                'verbose_name': 'Encaminhamento',
                'verbose_name_plural': 'Encaminhamentos',
            },
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('tipo', models.CharField(choices=[('ANALISE', 'Análise'), ('APROVACAO', 'Aprovação'), ('EXECUCAO', 'Execução'), ('REVISAO', 'Revisão'), ('FINALIZACAO', 'Finalização')], default='EXECUCAO', max_length=20, verbose_name='Tipo')),
                ('ordem', models.PositiveIntegerField(verbose_name='Ordem')),
                ('prazo_dias', models.PositiveIntegerField(default=5, verbose_name='Prazo (dias)')),
                ('permite_anexos', models.BooleanField(default=True, verbose_name='Permite Anexos')),
                ('requer_aprovacao', models.BooleanField(default=False, verbose_name='Requer Aprovação')),
            ],
            options={
                'verbose_name': 'Etapa',
                'verbose_name_plural': 'Etapas',
                'ordering': ['template', 'ordem'],
            },
        ),
        migrations.CreateModel(
            name='EtapaExecutada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('resultado', models.CharField(choices=[('APROVADO', 'Aprovado'), ('REJEITADO', 'Rejeitado'), ('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído')], default='CONCLUIDO', max_length=20, verbose_name='Resultado')),
                ('data_inicio', models.DateTimeField(auto_now_add=True, verbose_name='Data de Início')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('tempo_execucao', models.DurationField(blank=True, null=True, verbose_name='Tempo de Execução')),
            ],
            options={
                'verbose_name': 'Etapa Executada',
                'verbose_name_plural': 'Etapas Executadas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.CreateModel(
            name='LogAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(choices=[('INICIO', 'Início de Processo'), ('EXECUCAO_ETAPA', 'Execução de Etapa'), ('ENCAMINHAMENTO', 'Encaminhamento'), ('ANEXO_DOCUMENTO', 'Anexo de Documento'), ('APROVACAO', 'Aprovação'), ('REJEICAO', 'Rejeição'), ('CANCELAMENTO', 'Cancelamento'), ('CONCLUSAO', 'Conclusão')], max_length=30, verbose_name='Ação')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
            ],
            options={
                'verbose_name': 'Log de Auditoria',
                'verbose_name_plural': 'Logs de Auditoria',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoInstancia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(help_text='Gerado automaticamente', max_length=50, unique=True, verbose_name='Número do Processo')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('INICIADO', 'Iniciado'), ('EM_ANDAMENTO', 'Em Andamento'), ('AGUARDANDO', 'Aguardando'), ('CONCLUIDO', 'Concluído'), ('CANCELADO', 'Cancelado')], default='INICIADO', max_length=20, verbose_name='Status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_conclusao', models.DateTimeField(blank=True, null=True, verbose_name='Data de Conclusão')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processos',
                'ordering': ['-data_criacao'],
            },
        ),
        migrations.CreateModel(
            name='TemplateProcesso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('data_atualizacao', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
            ],
            options={
                'verbose_name': 'Template de Processo',
                'verbose_name_plural': 'Templates de Processos',
                'ordering': ['nome'],
            },
        ),
    ]
