# Generated by Django 4.2.25 on 2025-10-17 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templateprocesso',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='processoinstancia',
            name='criado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por'),
        ),
        migrations.AddField(
            model_name='processoinstancia',
            name='etapa_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_nesta_etapa', to='processos.etapa', verbose_name='Etapa Atual'),
        ),
        migrations.AddField(
            model_name='processoinstancia',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='instancias', to='processos.templateprocesso', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='processoinstancia',
            name='usuario_atual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processos_atuais', to=settings.AUTH_USER_MODEL, verbose_name='Usuário Atual'),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='etapa_executada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='processos.etapaexecutada', verbose_name='Etapa Executada'),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='processos.processoinstancia', verbose_name='Processo'),
        ),
        migrations.AddField(
            model_name='logauditoria',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='Usuário'),
        ),
        migrations.AddField(
            model_name='etapaexecutada',
            name='etapa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='execucoes', to='processos.etapa', verbose_name='Etapa'),
        ),
        migrations.AddField(
            model_name='etapaexecutada',
            name='executado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='etapas_executadas', to=settings.AUTH_USER_MODEL, verbose_name='Executado por'),
        ),
        migrations.AddField(
            model_name='etapaexecutada',
            name='processo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas_executadas', to='processos.processoinstancia', verbose_name='Processo'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etapas', to='processos.templateprocesso', verbose_name='Template'),
        ),
        migrations.AddField(
            model_name='etapa',
            name='usuarios_permitidos',
            field=models.ManyToManyField(blank=True, related_name='etapas_permitidas', to=settings.AUTH_USER_MODEL, verbose_name='Usuários Permitidos'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='etapa_destino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamentos_destino', to='processos.etapa', verbose_name='Etapa de Destino'),
        ),
        migrations.AddField(
            model_name='encaminhamento',
            name='etapa_origem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='encaminhamentos_origem', to='processos.etapa', verbose_name='Etapa de Origem'),
        ),
        migrations.AddField(
            model_name='documento',
            name='enviado_por',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por'),
        ),
        migrations.AddField(
            model_name='documento',
            name='etapa_executada',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='processos.etapaexecutada', verbose_name='Etapa Executada'),
        ),
        migrations.AlterUniqueTogether(
            name='etapa',
            unique_together={('template', 'ordem')},
        ),
        migrations.AlterUniqueTogether(
            name='encaminhamento',
            unique_together={('etapa_origem', 'etapa_destino', 'condicao')},
        ),
    ]
